simple pyproject.toml with uv
tfeldmann/organize pull request #423
Opened 2024-11-25 22:00 UTC by adfaure

## Change Summary

Simply add a `pyproject.toml` that should work with `uv`.

I wanted to play along with uv, it was the perfect occasion. So far, I was able to run the tests with the following command.
I also updated the CI, and it seems to work (the windows bug is also present upstream).

```
uv run python -m pytest tests
```

2024-11-27 11:55 UTC, tfeldmann requested changes
Thanks for the PR. Some changes are required before this can be merged :)

2024-11-27 11:55 UTC, tfeldmann commented on pyproject.toml
> +requires-python = ">=3.12"
We should support python >= 3.9

2024-11-27 11:55 UTC, tfeldmann commented on flake.nix
This seems to be commited by accident?

2024-11-27 11:55 UTC, tfeldmann commented on pyproject.toml
> +    "pdfminer-six>=20231228,<20231229",
pdfminer constraints can be relaxed ;)

2024-11-27 11:55 UTC, tfeldmann commented on .github/workflows/tests.yml
> -      - main
This should be reverted to `main` as you said

2024-12-05 20:32 UTC, adfaure commented
Hi,

I added a build system using `setuptools` to confirm that the project can still be built for Nix—it works as expected.

Additionally, I successfully built the documentation with MkDocs using the following commands:
```
uv run python -m mkdocs serve
uv sync --extra docs
```

2025-05-28 13:57 UTC, merged